name: "tiller-rbac"
version: "0.6.0"
usage: "Add RBAC profiles to Tiller"
description: |-
  This plugin allows you to configure Tiller with an RBAC profile.
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/tiller-rbac"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
